-- Generated by DSG App Builder runtime for job 9da2e174-1083-4d3a-a337-bc01c37763df
-- Goal: สร้างแอป PC เสมือนที่มี Windows ต่อเน็ตแล้ว มีจอมอนิเตอร์ในแอป มี remote mouse API ให้ agent จากที่อื่นควบคุมเมาส์ได้ และมี DSG governance ตรวจ invariant ก่อนทุก action พร้อม audit/evidence proof

create extension if not exists pgcrypto;

create table if not exists generated_app_items (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists generated_app_items_app_id_created_at_idx
  on generated_app_items(app_id, created_at desc);

alter table generated_app_items enable row level security;
