-- Generated by DSG App Builder runtime for job 56d6d778-d653-4df6-95b4-a4b6ca8ce4c0
-- Goal: สร้างสร้างแอป PC เสมือนที่มี Windows ต่อเน็ตแล้ว มีจอมอนิเตอร์ในแอป มี remote mouse API ให้ agent จากที่อื่นควบคุมเมาส์ได้ และมี DSG governance ตรวจ invariant ก่อนทุก action พร้อม audit/evidence proof ติดตั้ง ollma ai ในคอมเสมือนด้วย โดยให้ผู้ใช้ทำงานหลักได้: ลบข้อมูล, ดูรายการ, เพิ่มข้อมูล, ค้นหา, แสดงสถานะ. รูปแบบหน้าจอ: มือถือก่อน, อ่านง่าย, เรียบหรู, ทอง / แดง / เงิน, จอมอนิเตอร์สด. ต้องแสดงเฉพาะข้อมูลจริง มีหลักฐานการทำงาน และไม่ใช้ข้อมูลจำลอง.

create extension if not exists pgcrypto;

create table if not exists generated_app_items (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists generated_app_items_app_id_created_at_idx
  on generated_app_items(app_id, created_at desc);

alter table generated_app_items enable row level security;
