-- Generated by DSG App Builder runtime for job b25cbd5f-aa54-45f8-b3a4-5758ae6a486c
-- Goal: Create the missing DSG agent capability: https://dsg-one-v1.vercel.app/generated-apps/5b5ecf71-6bdf-47a6-bd16-bdfc19a9e32e. User benefit: User gets a concrete governed action instead of a dead button.

create extension if not exists pgcrypto;

create table if not exists generated_app_items (
  id uuid primary key default gen_random_uuid(),
  app_id text not null,
  title text not null,
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists generated_app_items_app_id_created_at_idx
  on generated_app_items(app_id, created_at desc);

alter table generated_app_items enable row level security;
