export default function GeneratedWorkerAppPage() {
  return (
    <main className="min-h-screen bg-slate-950 px-6 py-10 text-slate-100">
      <section className="mx-auto max-w-4xl rounded-3xl border border-indigo-500/30 bg-indigo-500/10 p-8">
        <p className="text-xs font-bold uppercase tracking-[0.24em] text-indigo-200">DSG Agent Worker App</p>
        <h1 className="mt-4 text-4xl font-black tracking-tight">สร้างแอปใหม่ที่ต้องการ</h1>
        <p className="mt-4 text-sm leading-7 text-slate-300">
          Generated by DSG CI worker. Production-ready claim remains blocked until CI, deploy, database, and live proof pass.
        </p>
        <div className="mt-6 rounded-2xl border border-amber-400/40 bg-amber-500/10 p-4 text-sm text-amber-100">
          productionReadyClaim: false
        </div>
      </section>
    </main>
  );
}
